### PR TITLE
Update colors for compatibility with the dark theme

### PR DESCRIPTION
**Pull request by spikenn**

### CODE REVIEW

**Comment by zerolab** [comment]
Hey @spikenn,

Would be good to have some screenshots -- before & after with the dark theme, and how the changes look with Wagtail 4.1

**Comment by spikenn** [comment]
Hi @zerolab

[Wagtail 4.1.6](https://i.imgur.com/QeW7ri3.png) - some CSS variables are missing
[Wagtail 5 (dark, before)](https://i.imgur.com/GMImDbm.png)
[Wagtail 5 (dark, after)](https://i.imgur.com/v4P3lzZ.png)
[Wagtail 5 (light, after)](https://i.imgur.com/USJLfL3.png)

**Comment by spikenn** [comment]
@zerolab I added fallback values, now it looks better.

[Wagtail 4.1.6](https://i.imgur.com/06V0qj6.png)

**Comment by zerolab** [comment]
That is most excellent, thank you @spikenn 

Will test locally this evening and if all is good, will merge and package it all up for a release

**Comment by zerolab** [comment]
By way of update -- this needs more work on consistency. I am chipping away slowly at it. May be a Friday release

**Comment by zerolab** [comment]
Merged manually in b60a60056452f6e06dd588bb16411619f3cd0e0d + parents.
Thank you @spikenn

**Comment by zerolab** [comment]
v1.5.1 is now published

**Pull request closed without merging**
