### PR TITLE
Translation of models with ParentalManyToManyField

### LINKED ISSUE #563: SynchronizedField for a ParentalManyToManyField leads to TypeError: 'DeferringManyRelatedManager' object is not iterable
Hello,
I have a translatable snippet with a `ParentalManyToManyField` to another model and want it to be synchronized. But when trying to translate this page I get the following exception:

```
Traceback (most recent call last):
  File "/Users/herbert/dev/python/wagtail-localize/wagtail_localize/tests/test_translation_model.py", line 721, in test_parental_many_to_many
    translation.save_target()
  File "/Users/herbert/dev/python/wagtail-localize/wagtail_localize/models.py", line 1340, in save_target
    self.source.create_or_update_translation(
  File "/Users/herbert/dev/python/wagtail-localize/wagtail_localize/models.py", line 762, in create_or_update_translation
    copy_synchronised_fields(original, translation)
  File "/Users/herbert/dev/python/wagtail-localize/wagtail_localize/fields.py", line 296, in copy_synchronised_fields
    setattr(target, field.attname, getattr(source, field.attname))
  File "/Users/herbert/dev/python/wagtail-localize/venv/lib/python3.9/site-packages/modelcluster/fields.py", line 490, in __set__
    manager.set(value)
  File "/Users/herbert/dev/python/wagtail-localize/venv/lib/python3.9/site-packages/modelcluster/fields.py", line 424, in set
    objs = list(objs)
TypeError: 'DeferringManyRelatedManager' object is not iterable
```

I have created a quick repro test here: 

https://github.com/hpoul/wagtail-localize/blob/64766882587d02b64822e903a21842b3c829e38f/wagtail_localize/test/models.py#L61-L68

and

https://github.com/hpoul/wagtail-localize/blob/64766882587d02b64822e903a21842b3c829e38f/wagtail_localize/tests/test_translation_model.py#L708-L725

```python
@register_snippet
class TestParentalSnippet(TranslatableMixin, models.Model):
    field = ParentalManyToManyField(
        TestUUIDModel,
        blank=True,
    )

    translatable_fields = [SynchronizedField("field")]
```

and

```python
    def test_parental_many_to_many(self):
        foreign_key_target = TestUUIDModel.objects.create(charfield="Some Test")
        snippet = TestParentalSnippet.objects.create()
        snippet.field = [foreign_key_target]

        source, created = TranslationSource.get_or_create_from_instance(snippet)
        translation = Translation.objects.create(
            source=source,
            target_locale=self.fr_locale,
        )

        translation.save_target()
```

Am I doing something wrong? Should `ParentalManyToManyField` be supported to be a synchronized field?

thanks,
  Herbert

### PR DESCRIPTION
**Pull request by hpoul**
My try to fix #563 
I basically duplicated the code from django-modelcluster `copy_cluster`: https://github.com/wagtail/django-modelcluster/blob/8666f16eaf23ca98afc160b0a4729864411c0563/modelcluster/models.py#L386-L392

### CODE REVIEW

**Review by zerolab — CHANGES_REQUESTED** [review]
Hey @hpoul,

Thank you for this PR. Can you rebase on latest `main` and re-generate the migration? we reduced the test app migrations to just `0001_initial`

This works well to sync the values, but they are not exposed in the edit translation UI which could potentially cause additional confusion

Could you look at handling that too, especially when it comes to Page models. https://github.com/wagtail/wagtail-localize/blob/main/wagtail_localize/views/edit_translation.py#L466-L516 is how that is happening at the moment

**Comment by hpoul** [comment]
@zerolab thanks for taking a look

> Can you rebase on latest `main` and re-generate the migration? we reduced the test app migrations to just `0001_initial`

i've now rebased. I'm not sure about the migrations.. i've deleted the old once and recreated a new one.. Was this what you meant, or should it also be part of the `0001_initial` migration? 🤔
 
> This works well to sync the values, but they are not exposed in the edit translation UI which could potentially cause additional confusion

Are `SynchronizedField`s actually exposed in the translation UI? 🤔 Should this simply list the selected IDs or `str()` of the objects?

Would it be possible to make this as part of a separate PR? This error blocks me from translating some content in my project.. hopefully the last problem 😬

btw. do you know of some easy way to use a forked version as a dependency? The problem is including `wagtail-localize` as a git dependency doesn't work because it would require manual `npm build` to generate the static files.. 🤔 I guess I could just commit the generated files into my forked git repo, but that would make merging pretty cumbersome..

**Comment by zerolab** [comment]
On using a fork.. you cannot really do it because of the FE assets.. best to build it locally and host the built package somewhere you can install from a URL

Will revisit the synchedfield question tomorrow.

**Comment by zemogle** [comment]
Did this make it into v1.2? I'm having the exact same problem.

**Comment by lvonlanthen** [comment]
@hpoul I am having the same problem and your fix would be very useful. It has been a while, but what is the state of this PR? Is there a way to help you getting this PR merged? Thanks!

**Comment by hpoul** [comment]
@lvonlanthen see https://github.com/wagtail/wagtail-localize/pull/564#pullrequestreview-964839332

> This works well to sync the values, but they are not exposed in the edit translation UI which could potentially cause additional confusion

I don't have enough time it understanding in the inner workings of the wagtail admin to fix this.. feel free to take over this PR.. 🤷‍♂️

**Comment by hpoul** [comment]
I've rebased on main and squashed commits.. is there any chance to get this merged without the UI when it's not synchronized? @zerolab  At least it fixes the exception when creating the translation.. I don't see how it would make anything worse..

**Review by zerolab — APPROVED** [review]

**Comment by zerolab** [comment]
@hpoul now in https://github.com/wagtail/wagtail-localize/releases/tag/v1.6
sorry for the delay!

**Pull request merged**
