### PR TITLE
Be more defensive with fetching schema version from Django migration records

### LINKED ISSUE #706: Tests fail when using pytest with SQLite and TranslationSource.get_or_create_from_instance
wagtail = "4.2"
wagtail-localize = "^1.4"

We are running tests using `pytest` with the `--nomigrations` flag and SQLite as the db backend.

When running tests involving `TranslationSource.get_or_create_from_instance`, the tests fail with the following error:

```
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/wagtail_localize/models.py:381: in get_or_create_from_instance
    "schema_version": get_schema_version(instance._meta.app_label) or "",
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/wagtail_localize/models.py:136: in get_schema_version
    .last()
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/cacheops/query.py:363: in last
    return self._no_monkey.last(self)
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/django/db/models/query.py:1055: in last
    for obj in (self.reverse() if self.ordered else self.order_by("-pk"))[:1]:
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/django/db/models/query.py:394: in __iter__
    self._fetch_all()
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/cacheops/query.py:273: in _fetch_all
    return self._no_monkey._fetch_all(self)
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/django/db/models/query.py:1867: in _fetch_all
    self._result_cache = list(self._iterable_class(self))
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/django/db/models/query.py:87: in __iter__
    results = compiler.execute_sql(
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py:1398: in execute_sql
    cursor.execute(sql, params)
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/cacheops/transaction.py:98: in execute
    result = self._no_monkey.execute(self, sql, params)
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/django/db/backends/utils.py:67: in execute
    return self._execute_with_wrappers(
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/django/db/backends/utils.py:80: in _execute_with_wrappers
    return executor(sql, params, many, context)
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/django/db/backends/utils.py:84: in _execute
    with self.db.wrap_database_errors:
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/django/db/utils.py:91: in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
/root/.cache/pypoetry/virtualenvs/.venv/lib/python3.10/site-packages/django/db/backends/utils.py:89: in _execute
    return self.cursor.execute(sql, params)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0xffffb63171c0>
query = 'SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" WHERE "django_migrations"."app" = ? ORDER BY "django_migrations"."applied" DESC LIMIT 1'
params = ('core',)

    def execute(self, query, params=None):
        if params is None:
            return Database.Cursor.execute(self, query)
        query = self.convert_query(query)
>       return Database.Cursor.execute(self, query, params)
E       django.db.utils.OperationalError: no such table: django_migrations
```

This looks like it's because `MigrationRecorder` is being used here: 

https://github.com/wagtail/wagtail-localize/blob/v1.4/wagtail_localize/models.py#L139

Is there a way around this for testing `TranslationSource` using `pytest` and `SQLite`?

### PR DESCRIPTION
**Pull request by zerolab**
Fixes #706

### CODE REVIEW

**Comment by zerolab** [comment]
Here's the packaged version for this PR
[wagtail_localize-1.5.2a1.tar.gz](https://github.com/wagtail/wagtail-localize/files/12538072/wagtail_localize-1.5.2a1.tar.gz)


@urlsangel any chance you could give it a spin?

**Comment by urlsangel** [comment]
> Here's the packaged version for this PR [wagtail_localize-1.5.2a1.tar.gz](https://github.com/wagtail/wagtail-localize/files/12538072/wagtail_localize-1.5.2a1.tar.gz)
> 
> @urlsangel any chance you could give it a spin?

@zerolab Sure thing, I'll attempt to do so in the next hour or so 👍

**Review by urlsangel — COMMENTED** [review]
@zerolab 

Tests pass for me locally when when using this version, great work 👍

**Comment by drcongo** [comment]
@zerolab I'm working on the same project as @urlsangel so consider it fixed for me too. Thank you!

**Comment by zerolab** [comment]
Great to hear. Will merge and get a release out tomorrow morning

**Comment by zerolab** [comment]
https://pypi.org/project/wagtail-localize/

**Pull request merged**
