### PR TITLE
Change dependencies to allow Django 4.2.

### PR DESCRIPTION
**Pull request by kmtracey**
Add tox envs for combos of Python with Django 4.2 and Wagtail 5.0. Refs #691

### CODE REVIEW

**Comment by kmtracey** [comment]
Screenshot from 2023-05-10 13-21-37

Sigh, github actions had some issue. FWIW I did get a successful tox run locally (overnight :-)) after these changes.

```
  python3.7-django3.2-wagtail4.1-sqlite: OK (462.93=setup[0.10]+cmd[462.82] seconds)
  python3.7-django3.2-wagtail4.1-postgres12: OK (395.96=setup[0.02]+cmd[395.94] seconds)
  python3.7-django3.2-wagtail4.2-sqlite: OK (471.86=setup[81.17]+cmd[390.69] seconds)
  python3.7-django3.2-wagtail4.2-postgres12: OK (386.98=setup[57.90]+cmd[329.08] seconds)
  python3.8-django3.2-wagtail4.1-sqlite: OK (445.49=setup[58.77]+cmd[386.71] seconds)
  python3.8-django3.2-wagtail4.1-postgres12: OK (510.32=setup[72.01]+cmd[438.32] seconds)
  python3.8-django3.2-wagtail4.2-sqlite: OK (479.95=setup[72.98]+cmd[406.96] seconds)
  python3.8-django3.2-wagtail4.2-postgres12: OK (393.65=setup[65.93]+cmd[327.72] seconds)
  python3.9-django3.2-wagtail4.1-sqlite: OK (316.12=setup[64.46]+cmd[251.66] seconds)
  python3.9-django3.2-wagtail4.1-postgres12: OK (271.50=setup[43.96]+cmd[227.54] seconds)
  python3.9-django3.2-wagtail4.2-sqlite: OK (231.94=setup[43.80]+cmd[188.14] seconds)
  python3.9-django3.2-wagtail4.2-postgres12: OK (192.09=setup[32.62]+cmd[159.47] seconds)
  python3.10-django3.2-wagtail4.1-sqlite: OK (223.78=setup[32.07]+cmd[191.71] seconds)
  python3.10-django3.2-wagtail4.1-postgres12: OK (271.89=setup[45.07]+cmd[226.82] seconds)
  python3.10-django3.2-wagtail4.2-sqlite: OK (273.92=setup[44.23]+cmd[229.70] seconds)
  python3.10-django3.2-wagtail4.2-postgres12: OK (276.84=setup[43.96]+cmd[232.88] seconds)
  python3.8-django4.0-wagtail4.1-sqlite: OK (262.62=setup[44.87]+cmd[217.75] seconds)
  python3.8-django4.0-wagtail4.1-postgres15: OK (188.70=setup[32.71]+cmd[155.98] seconds)
  python3.8-django4.0-wagtail4.2-sqlite: OK (189.94=setup[32.51]+cmd[157.43] seconds)
  python3.8-django4.0-wagtail4.2-postgres15: OK (232.98=setup[33.29]+cmd[199.69] seconds)
  python3.8-django4.1-wagtail4.1-sqlite: OK (260.74=setup[43.42]+cmd[217.33] seconds)
  python3.8-django4.1-wagtail4.1-postgres15: OK (260.89=setup[43.55]+cmd[217.34] seconds)
  python3.8-django4.1-wagtail4.2-sqlite: OK (224.48=setup[44.94]+cmd[179.54] seconds)
  python3.8-django4.1-wagtail4.2-postgres15: OK (186.00=setup[33.50]+cmd[152.50] seconds)
  python3.9-django4.0-wagtail4.1-sqlite: OK (188.30=setup[32.06]+cmd[156.24] seconds)
  python3.9-django4.0-wagtail4.1-postgres15: OK (211.44=setup[32.10]+cmd[179.34] seconds)
  python3.9-django4.0-wagtail4.2-sqlite: OK (270.55=setup[43.21]+cmd[227.35] seconds)
  python3.9-django4.0-wagtail4.2-postgres15: OK (269.29=setup[44.00]+cmd[225.29] seconds)
  python3.9-django4.1-wagtail4.1-sqlite: OK (220.99=setup[43.63]+cmd[177.36] seconds)
  python3.9-django4.1-wagtail4.1-postgres15: OK (182.95=setup[32.47]+cmd[150.48] seconds)
  python3.9-django4.1-wagtail4.2-sqlite: OK (183.39=setup[32.11]+cmd[151.28] seconds)
  python3.9-django4.1-wagtail4.2-postgres15: OK (220.57=setup[32.67]+cmd[187.91] seconds)
  python3.10-django4.0-wagtail4.1-sqlite: OK (269.60=setup[45.88]+cmd[223.72] seconds)
  python3.10-django4.0-wagtail4.1-postgres15: OK (268.01=setup[45.32]+cmd[222.69] seconds)
  python3.10-django4.0-wagtail4.2-sqlite: OK (213.52=setup[44.94]+cmd[168.59] seconds)
  python3.10-django4.0-wagtail4.2-postgres15: OK (191.34=setup[34.75]+cmd[156.59] seconds)
  python3.10-django4.1-wagtail4.1-sqlite: OK (183.42=setup[32.91]+cmd[150.51] seconds)
  python3.10-django4.1-wagtail4.1-postgres15: OK (249.68=setup[34.69]+cmd[214.99] seconds)
  python3.10-django4.1-wagtail4.2-sqlite: OK (398.95=setup[45.71]+cmd[353.25] seconds)
  python3.10-django4.1-wagtail4.2-postgres15: OK (344.74=setup[49.83]+cmd[294.90] seconds)
  python3.8-django4.2-wagtail5.0-sqlite: OK (246.42=setup[41.68]+cmd[204.74] seconds)
  python3.8-django4.2-wagtail5.0-postgres15: OK (238.99=setup[42.71]+cmd[196.29] seconds)
  python3.9-django4.2-wagtail5.0-sqlite: OK (182.04=setup[43.34]+cmd[138.70] seconds)
  python3.9-django4.2-wagtail5.0-postgres15: OK (169.81=setup[33.05]+cmd[136.76] seconds)
  python3.10-django4.2-wagtail5.0-sqlite: OK (167.96=setup[31.63]+cmd[136.33] seconds)
  python3.10-django4.2-wagtail5.0-postgres15: OK (170.05=setup[33.77]+cmd[136.28] seconds)
  python3.11-django4.1-wagtail4.1-sqlite: OK (182.29=setup[31.30]+cmd[150.99] seconds)
  python3.11-django4.1-wagtail4.1-postgres15: OK (251.75=setup[42.61]+cmd[209.14] seconds)
  python3.11-django4.1-wagtail4.2-sqlite: OK (248.76=setup[43.22]+cmd[205.54] seconds)
  python3.11-django4.1-wagtail4.2-postgres15: OK (245.24=setup[43.06]+cmd[202.18] seconds)
  python3.11-django4.2-wagtail5.0-sqlite: OK (192.85=setup[42.55]+cmd[150.30] seconds)
  python3.11-django4.2-wagtail5.0-postgres15: OK (177.15=setup[35.52]+cmd[141.64] seconds)
  congratulations :) (13751.86 seconds)
```

**Comment by kmtracey** [comment]
> Re-ran the failed Python jobs and all is green `¯\_(ツ)_/¯`
> 

Thanks! It seemed like github actions was having some trouble that day...

**Comment by mihalikv** [comment]
Do you plan to release a new version with Django 4.2 support?
Thanks.

**Comment by zerolab** [comment]
Yes. Soon

**Comment by zerolab** [comment]
v1.5.1 is now out with Django 4.2 and Wagtail 5.0

**Pull request merged**
