### PR TITLE
Fix Revision model change in Wagtail 4.0

### LINKED ISSUE #629: Migration fail installing wagtail-localize fresh on a wagtail 4.1 project
I was trying to add 1.3a4 to a project that I had already upgraded to wagtail 4, and end up with 
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration wagtailcore.0059_apply_collection_ordering is applied before its dependency wagtail_localize.0001_initial

If I understand this correctly the run_before line in the 0001 migration that was added in #616 will cause a failure for everyone trying to install wagtail-localize after they have already run migrate 0059 (I am at 0076 at the moment)

### PR DESCRIPTION
**Pull request by zerolab**
this should cover:
- adding localize to a Wagtail 4 project
- upgrading a project using localize to Wagtail 4

Fixes #629

### CODE REVIEW

**Comment by zerolab** [comment]
@ArnarTumi any chance you could test this on your projects `pip install git+https://github.com/wagtail/wagtail-localize.git@fix/pagerevision-revision-switcharoo-dance`. Note that installing it this way won't have the compiled assets so the edit translation view will error. Should not matter as you're testing adding localize to an existing project. If you have any on pre 4.0, would be nice to try it on them too

cc @iscilyas in the context of #615 too

**Comment by zerolab** [comment]
@gasman will merge this as is tomorrow mid-morning, unless I hear otherwise

**Review by gasman — APPROVED** [review]
LGTM! This looks like a very neat way of dealing with the unpredictability of the model name. I look forward to stealing it for wagtail-review :-)

**Comment by zerolab** [comment]
Thank you! it took quite some trial and error. Lots of TILs in the process. I am both in awe and somewhat mystified by the power of Django migrations

**Pull request merged**
