### PR TITLE
updating tests as .assertFormError() is removed in Django 5

### PR DESCRIPTION
**Pull request by softquantum**

### CODE REVIEW

**Comment by softquantum** [comment]
I tested with tox locally and all tests passed, why is the test deployment failing ?

**Comment by zerolab** [comment]
Those are Netlify errors (on the list to move away from hosting docs there)
Just triggered the proper CI jobs.

Also, any chance you could fold in the changes from #747? So as to actually test with Django 5.0

**Comment by softquantum** [comment]
> Those are Netlify errors (on the list to move away from hosting docs there) Just triggered the proper CI jobs.
> 
> Also, any chance you could fold in the changes from #747? So as to actually test with Django 5.0

Will check

**Comment by zerolab** [comment]
I am happy to merge this as is, and we can focus on the rest of the errors.
Not sure what's happening there without looking into it, to be honest.

Will try to have a bit of a dig tomorrow morning, unless you beat me to it

**Comment by softquantum** [comment]
Will try to do it before ;)

**Pull request merged**
